//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_music.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALBUM()
        {
            this.SONGs = new HashSet<SONG>();
        }
    
        public int ID_ALBUM { get; set; }
        public string NAME_ALBUM { get; set; }
        public Nullable<int> ID_SINGER { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string PICTURE_ALBUM { get; set; }
    
        public virtual GENRE GENRE { get; set; }
        public virtual SINGER SINGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONG> SONGs { get; set; }
    }
}
